
try {
	throw Exception('foo');
} catch(err) {

}
